config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root "cheeses#index"
  resources :favorites
  resources :cheeses
  resources :users

end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
  has_many :favorites
  has_many :users, :through => :favorites
  accepts_nested_attributes_for :users

  def fav_count
    favorites.count
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :cheese
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :favorites
  has_many :cheeses, :through => :favorites
  accepts_nested_attributes_for :cheeses


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  def index
    @cheeses = Cheese.all.sort_by{ |cheese| cheese.fav_count}.reverse!
  end

  def show
    @cheese = Cheese.find(params[:id])
    @users = @cheese.users
  end

  def new
    @cheese = Cheese.new
  end

  def create
    @cheese = Cheese.new(cheese_params)

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
        format.json { render :show, status: :created, location: @cheese }
      else
        format.html { render :new }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    def set_cheese
      @cheese = Cheese.find(params[:id])
    end

    def cheese_params
      params.require(:cheese).permit(:name, user_ids: [])
    end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  skip_before_action :authenticate_user, only: [:new, :create]


  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      redirect_to new_user_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @cheeses = @user.cheeses
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    set_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest, cheese_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="new-name">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheeses/index.html.erb
</br>
</br>
</br>
</br>

<h1>🧀 List of Cheeses 🧀</h1>
<% if logged_in? %>
<h3>Hello <%= current_user.username %>!</h3>
<% end %>

<%= react_component('CheeseIndex', cheese: @cheeses) %>

<table class="table table-striped">
  <thead class="table table-striped">
    <tr>
      <th>Name:</th>
      <th>Likes:</th>
      <th>Link:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cheeses.each do |cheese| %>
      <tr>
        <td><%= cheese.name %></td>
        <td><%= cheese.favorites.count%> Likes</td>
        <td><%= link_to 'Show', cheese %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
<%= link_to 'New Cheese', new_cheese_path %>
<% end %>

app/views/cheeses/new.html.erb
</br>
</br>
</br>
</br>

<h1>New Cheese</h1>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
</br>
</br>
</br>
</br>

<p>
  <strong>Name:</strong>
  <%= @cheese.name %>
  <p><strong>Users who like this cheese:</strong></p>
  <ol>
  <% @cheese.users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
  </ol>

</p>




<%= link_to 'Back', cheeses_path %>

app/views/favorites/index.html.erb
<%= simple_form_for current_user do |f| %>
   <%= f.association :cheeses, as: :check_boxes,collection: Cheese.all %>
   <%= f.submit 'Save Favorite Cheeses' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactAndCheese</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if logged_in? %>
    <%= react_component("NavBar") %>
  <% else %>
    <%= react_component("LoggedOutNavBar") %>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
</br>
</br>
</br>
</br>

<h1>👦 List of Users  👧</h1>
<% if logged_in? %>
<h3>Hello <%= current_user.username %>!</h3>
<% end %>
<table class="table table-striped">
  <thead class="table table-striped">
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<br/>
<br/>
<br/>
<br/>

<h1>New User</h1>

<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
</br>
</br>
</br>
</br>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Favorite Cheeses:</strong>
  <% @cheeses.each do |cheese| %>
      <%= cheese.name %>
      <%= link_to 'Show', cheese %>
  <% end %>
</p>

<%= link_to 'Back', users_path %>